sudo: required

services:
  - docker

before_install:
  - docker build -t stephenc0821/docker-react -f Dockerfile.dev . # docker user and repo name

script: #commands to run test suite
  - docker run -e CI=true stephenc0821/docker-react npm run test #need zero exit code for travis so run w/ CI env flag

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-us-east-1-381492306175"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: "$AWS_FRONTEND_KEY"
  secret_access_key: "$AWS_FRONTEND_SECRET" #added aws cli keys/secret to travis settings
