sudo: required

services:
  - docker

before_install:
  - docker build -t stephenc0821/docker-react -f Dockerfile.dev . # docker user and repo name

script: #commands to run test suite
  - docker run -e CI=true stephenc0821/docker-react npm run test #need zero exit code for travis so run w/ CI env flag
